apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "faceit-db.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name | quote }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        chart: {{ template "faceit-db.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          lifecycle:
            preStop:
              exec:
                command:
                - sleep
                - "10"
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s-vars" .Release.Namespace .Chart.Name }}
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
          resources:
            {{- toYaml .Values.resources | nindent 13 }}

  #    imagePullSecrets:
  #      - name: regcred