apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "faceit-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name | quote }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        chart: {{ template "faceit-api.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          lifecycle:
            preStop:
              exec:
                command:
                - sleep
                - "10"
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 13 }}

  #    imagePullSecrets:
  #      - name: regcred